name: Output information
on: [workflow_dispatch,push]
jobs:
    info: 
        runs-on: ubuntu-latest
        steps:
            - name: output github context
              run: echo "${{toJson(github)}}"